# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
gems: [jekyll-paginate]
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
# disqus: dbyll
# google_analytics: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Android and More

title: Chievent
description: Blogs about programing especially Android programing by Chievent.
author:
  name: Chievent
  email: chievent@qq.com
  github: chievent
  # twitter: dbtek
  # pinterest: asd123
  # linkedin: asd123
  bio: Keep Struggling, Keep Programing.
  email_md5: 6aebf582aa05f2cc8dd19869a89c5a50

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
