# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
gems: [jekyll-paginate]
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown

# google_analytics_account: dbyll
tencent_analytics_signature: 53587127 # the signature; javascript 代码中"?"后面的一串数字
baidu_statistics_signature: 703d5f97a71de4295dddbe5205a83395 # the signature; javascript 代码中"?"后面的一串16进制数字

comments: 
  agent: duoshuo
  shortname: chievent

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Android and More
      layout: post
      comments: true

title: Chievent
description: Blogs about programing especially Android programing by Chievent.
author:
  name: Chievent
  avatar: /assets/avatars/avatar.png
  email: chievent@qq.com
  github: chievent
  # twitter: dbtek
  # pinterest: asd123
  # linkedin: asd123
  bio: Keep Struggling, Keep Programing.
  email_md5: 6aebf582aa05f2cc8dd19869a89c5a50

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
